# Generated by Django 5.0.6 on 2024-06-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_size_size_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
    ]
