# Generated by Django 5.0.6 on 2024-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_name_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='size_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
