# Generated by Django 5.0.6 on 2024-06-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_size_size_size_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.IntegerField(),
        ),
    ]
