# Generated by Django 5.0.6 on 2024-07-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_brand_image_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
