# Generated by Django 5.0.6 on 2024-07-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[(0, 'CONSULTA'), (1, 'RECLAMO'), (2, 'SUGERENCIA'), (3, 'FELICITACIONES')])),
                ('mensaje', models.TextField()),
                ('Avisos', models.BooleanField()),
            ],
        ),
    ]
